replicaCount: 1

image:
  repository: java-app
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: qa.chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: boardgame-qa-tls
      hosts:
        - qa.chart-example.local

resources:
  limits:
    cpu: 300m
    memory: 384Mi
  requests:
    cpu: 150m
    memory: 192Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

env: [ "qa" ]

application:
  properties:
    logging.level.root: INFO
