replicaCount: 1

image:
  repository: java-app
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: dev.chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: boardgame-dev-tls
      hosts:
        - dev.chart-example.local

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

env: [ "dev" ]

application:
  properties:
    logging.level.root: DEBUG
