name: Multi Environment DevSecOps GitOps Pipeline

on:
  push:
    branches:
      - dev
      - qa
      - stage
      - main

env:
  IMAGE_NAME: java-app

jobs:

  devsecops-pipeline:
    runs-on: ubuntu-latest

    steps:

    #################################################
    # Checkout Source Code
    #################################################

    - name: Checkout Code
      uses: actions/checkout@v4

    #################################################
    # Setup Java
    #################################################

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    #################################################
    # Cache Maven Dependencies
    #################################################

    - name: Cache Maven Packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2

    #################################################
    # Detect Environment
    #################################################

    - name: Detect Environment
      run: |
        BRANCH_NAME=${GITHUB_REF##*/}

        if [ "$BRANCH_NAME" = "dev" ]; then
          echo "ENV=dev" >> $GITHUB_ENV

        elif [ "$BRANCH_NAME" = "qa" ]; then
          echo "ENV=qa" >> $GITHUB_ENV

        elif [ "$BRANCH_NAME" = "stage" ]; then
          echo "ENV=stage" >> $GITHUB_ENV

        elif [ "$BRANCH_NAME" = "main" ]; then
          echo "ENV=prod" >> $GITHUB_ENV
        fi

    #################################################
    # Maven Build
    #################################################

    - name: Maven Build
      run: |
        mvn clean package -DskipTests

    #################################################
    # Run Unit Tests
    #################################################

    - name: Run Unit Tests
      run: |
        mvn test

    #################################################
    # SonarQube Scan
    #################################################

    - name: SonarQube Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn sonar:sonar \
        -Dsonar.projectKey=java-app-${ENV} \
        -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    #################################################
    # Sonar Quality Gate
    #################################################

    - name: SonarQube Quality Gate
      uses: sonarsource/sonarqube-quality-gate-action@master
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    #################################################
    # Install Trivy
    #################################################
      - name: Helm Lint
        run: |
          helm lint helm/
        sudo apt-get update -y
        sudo apt-get install wget apt-transport-https gnupg lsb-release -y

        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | \
      - name: Kubernetes Manifest Validation
        run: |
          helm template java-app helm \
          -f helm/values-${ENV}.yaml > rendered.yaml
        sudo tee /etc/apt/sources.list.d/trivy.list

        sudo apt-get update -y
        sudo apt-get install trivy -y
      - name: Update Helm Image Tag
        run: |
          sed -i "s/tag:.*/tag: \"$IMAGE_TAG\"/g" helm/values-${ENV}.yaml
    #################################################

    - name: Trivy Filesystem Scan
      run: |
      - name: Commit Helm Changes
        run: |
          git add helm/

          git commit -m "Updated ${ENV} image tag to $IMAGE_TAG" || echo "No Changes"
    #################################################
    # Trivy Secret Scan
    #################################################

    - name: Trivy Secret Scan
      run: |
        trivy fs . \
        --scanners secret \
        --severity HIGH,CRITICAL \
        --exit-code 0

    #################################################
    # Install Checkov
    #################################################

    - name: Install Checkov
      run: |
        pip install checkov -y

    #################################################
    # Checkov IaC Scan
    #################################################

    - name: Checkov Scan
      run: |
        checkov -d . \
        --framework kubernetes,dockerfile,github_actions,helm \
        --soft-fail

    #################################################
    # Dependency Vulnerability Scan
    #################################################

    - name: OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'java-app'
        path: '.'
        format: 'HTML'

    #################################################
    # Dockerfile Lint
    #################################################

    - name: Dockerfile Lint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile

    #################################################
    # Generate Image Tag
    #################################################

    - name: Generate Image Tag
      run: |
        echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    #################################################
    # Docker Build
    #################################################

    - name: Build Docker Image
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG .

    #################################################
    # Trivy Docker Image Scan
    #################################################

    - name: Trivy Docker Image Scan
      run: |
        trivy image $IMAGE_NAME:$IMAGE_TAG \
        --severity HIGH,CRITICAL \
        --format table \
        --exit-code 0

    #################################################
    # Generate SBOM
    #################################################

    - name: Generate SBOM
      run: |
        trivy image \
        --format cyclonedx \
        --output sbom.json \
        $IMAGE_NAME:$IMAGE_TAG

    #################################################
    # Install Helm
    #################################################

    - name: Install Helm
      uses: azure/setup-helm@v4

    #################################################
    # Helm Lint
    #################################################

    - name: Helm Lint
      run: |
        helm lint helm-chart/

    #################################################
    # Kubernetes Manifest Validation
    #################################################

    - name: Validate Kubernetes Manifests
      run: |
        helm template java-app helm-chart \
        -f helm-chart/values-${ENV}.yaml > rendered.yaml

    #################################################
    # Update Environment Specific values.yaml
    #################################################

    - name: Update Helm Image Tag
      run: |
        sed -i "s/tag:.*/tag: \"$IMAGE_TAG\"/g" helm-chart/values-${ENV}.yaml

    #################################################
    # Configure Git
    #################################################

    - name: Configure Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"

    #################################################
    # Commit Helm Changes
    #################################################

    - name: Commit Helm Changes
      run: |
        git add helm-chart/

        git commit -m "Updated ${ENV} image tag to $IMAGE_TAG" || echo "No Changes"

    #################################################
    # Push Helm Changes
    #################################################

    - name: Push Helm Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUBclassic_TOKEN }}
        branch: ${{ github.ref_name }}

    #################################################
    # Upload Security Reports
    #################################################

    - name: Upload Reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          dependency-check-report.html
          rendered.yaml
          sbom.json

    #################################################
    # Install kubectl
    #################################################

    - name: Install kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: latest

    #################################################
    # Configure kubeconfig
    #################################################

    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube

        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config

        chmod 600 ~/.kube/config

    #################################################
    # Verify Kubernetes Connection
    #################################################

    - name: Verify Kubernetes Connection
      run: |
        kubectl cluster-info
        kubectl get nodes

    #################################################
    # Verify ArgoCD Namespace
    #################################################

    - name: Verify ArgoCD Namespace
      run: |
        kubectl get ns argocd

    #################################################
    # Apply Environment Specific ArgoCD App
    #################################################

    - name: Apply ArgoCD Application
      run: |
        kubectl apply -f argocd/${ENV}-application.yaml --server-side

    #################################################
    # Verify ArgoCD Applications
    #################################################

    - name: Verify ArgoCD Applications
      run: |
        kubectl get applications -n argocd

    #################################################
    # Verify Sync Status
    #################################################

    - name: Verify Sync Status
      run: |
        kubectl get applications -n argocd -o wide

    #################################################
    # Verify Deployment Rollout
    #################################################

    - name: Verify Deployment Rollout
      run: |
        kubectl rollout status deployment/java-app \
        -n ${ENV} \
        --timeout=300s

    #################################################
    # Deployment Success
    #################################################

    - name: Deployment Status
      run: |
        echo "${ENV} Deployment Completed Successfully"
